"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.XRPL_NODE = exports.USER_1_SEED = exports.OPERATIONAL_WALLET_GBP_SEED = exports.ISSUER_WALLET_GBP_CURRENCY = exports.ISSUER_WALLET_GBP_SEED = exports.OPERATIONAL_WALLET_ETB_SEED = exports.ISSUER_WALLET_ETB_CURRENCY = exports.ISSUER_WALLET_ETB_SEED = void 0;
exports.ISSUER_WALLET_ETB_SEED = "sEdSRUJ3juriToePURnifLMkDSBTcNi";
exports.ISSUER_WALLET_ETB_CURRENCY = "USD";
exports.OPERATIONAL_WALLET_ETB_SEED = "sEdTZFu2PNQXPZyQCbzuGVmjp5BHdF3";
exports.ISSUER_WALLET_GBP_SEED = "sEd7QH3XnW2VQvfUJ1u6uZ6hFgKyxnL";
exports.ISSUER_WALLET_GBP_CURRENCY = "INR";
exports.OPERATIONAL_WALLET_GBP_SEED = "sEdVcHWLWjsDX8mj62HGAW9NUk44a4y";
exports.USER_1_SEED = "";
exports.XRPL_NODE = "wss://testnet.xrpl-labs.com/";
